# Generated by Django 2.2.4 on 2021-09-28 01:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('week', models.PositiveIntegerField(null=True)),
                ('season', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spread', models.PositiveIntegerField(default=2)),
                ('points_perfect', models.PositiveIntegerField(default=4)),
                ('points_score', models.PositiveIntegerField(default=1)),
                ('points_winner', models.PositiveIntegerField(default=4)),
                ('name', models.TextField()),
                ('season', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Game')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abbreviation', models.TextField()),
                ('color', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('altcolor', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='UserSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unc_wins', models.PositiveIntegerField(default=0)),
                ('unc_losses', models.PositiveIntegerField(default=0)),
                ('unc_place', models.PositiveIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('points_spread', models.PositiveIntegerField(default=0)),
                ('points_perfect', models.PositiveIntegerField(default=0)),
                ('points_ascore', models.PositiveIntegerField(default=0)),
                ('points_hscore', models.PositiveIntegerField(default=0)),
                ('points_winner', models.PositiveIntegerField(default=0)),
                ('leaguegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LeagueGame')),
                ('userseason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.UserSeason')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='schedule.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='schedule.Team'),
        ),
    ]
