# Generated by Django 2.2.4 on 2021-09-27 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.TextField()),
                ('away_team', models.TextField()),
                ('winner', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('season', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.TextField()),
                ('away_team', models.TextField()),
                ('start_date', models.DateTimeField(null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('week', models.PositiveIntegerField(null=True)),
                ('season', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spread', models.PositiveIntegerField(default=2)),
                ('points_perfect', models.PositiveIntegerField(default=4)),
                ('points_score', models.PositiveIntegerField(default=1)),
                ('points_winner', models.PositiveIntegerField(default=4)),
                ('name', models.TextField()),
                ('season', models.PositiveIntegerField()),
                ('points_bonus', models.PositiveIntegerField(default=4)),
                ('unc_place', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueBonusGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonusgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.BonusGame')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.League')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Game')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.League')),
            ],
        ),
        migrations.CreateModel(
            name='UserSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unc_wins', models.PositiveIntegerField(default=0)),
                ('unc_losses', models.PositiveIntegerField(default=0)),
                ('unc_place', models.PositiveIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBonusGamePick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LeagueBonusGame')),
                ('userseason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.UserSeason')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('points_spread', models.PositiveIntegerField(default=0)),
                ('points_perfect', models.PositiveIntegerField(default=0)),
                ('points_ascore', models.PositiveIntegerField(default=0)),
                ('points_hscore', models.PositiveIntegerField(default=0)),
                ('points_winner', models.PositiveIntegerField(default=0)),
                ('leaguegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LeagueGame')),
                ('userseason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.UserSeason')),
            ],
        ),
    ]
