# Generated by Django 2.2.4 on 2021-09-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.TextField(default='FBS'),
            preserve_default=False,
        ),
    ]
